config/routes.rb
Rails.application.routes.draw do
  root :to => 'courses#index'

  resources :courses
  resources :sections
  resources :lessons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :sections
  validates :title, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  validates :title, :content, :presence => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  belongs_to :course
  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to  courses_path
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course= Course.find(params[:id])
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:title)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = Lesson.find(params[:id])
    @section = Section.find(@lesson.section_id)
    @course = Course.find(@section.course_id)
  end

  def new
    @lesson = Lesson.new
    @section = Section.all
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to  courses_path
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
    @section = Section.all
  end

  def update
    @lesson= Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to section_path(@lesson.section_id)
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to section_path(@lesson.section_id)
  end

  private
  def lesson_params
    params.require(:lesson).permit(:title, :content, :section_id, :day, :lesson_type)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @section = Section.find(params[:id])
    @course = Course.find(@section.course_id)
  end

  def new
    @section = Section.new
    @course = Course.all
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to  courses_path
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
    @course = Course.all
  end

  def update
    @section= Section.find(params[:id])
    if @section.update(section_params)
      redirect_to course_path(@section.course_id)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to courses_path
  end

  private
  def section_params
    params.require(:section).permit(:title, :week, :course_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render "form" %>

app/views/courses/index.html.erb
<h1>Courses</h1>
<ul class="list-unstyled">
  <% @courses.each do |course| %>
    <li>
      <span class="redTitle">
        <%= link_to course.title, course_path(course) %>
      </span>
       / <%= link_to "Edit", edit_course_path(course) %> /
      <%= link_to "Delete", course_path(course),
                             :data => {:confirm => "Are you sure?",
                                            :method => "delete"} %>
    </li>
  <% end %>
</ul>

<p>© 2017 <span class="redTitle"><%= link_to "Rikidavus", new_course_path(@course) %></span>, Inc.</p>

app/views/courses/new.html.erb
<h1>Add Course</h1>

<%= render "form" %>

app/views/courses/show.html.erb
<h1><%= @course.title %></h1>
<hr>
<% if @course.sections.any? %>
  <ul class="list-unstyled">
    <% @course.sections.each do |section| %>
      <li>
        (<%= section.week %>)
        <span class="redTitle">
          <%= link_to section.title, section_path(section) %>
        </span>

        <%= link_to "Edit", edit_section_path(section) %> /
        <%= link_to "Delete", section_path(section),
                               :data => {:confirm => "Are you sure?",
                                              :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no sections yet!</p>
<% end %>

<p class="redTitle"><%= link_to "Return to courses", courses_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnHowToProgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for @lesson do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <% day = ['Weekend', 'Monday', 'Tuesday', 'Wednesday', 'Thursday'] %>
  <%= f.select :day,  day %>
  <% lessonType = ['Homework', 'Lesson'] %>
  <%= f.select :lesson_type,  lessonType %>
  <% options = options_from_collection_for_select(@section, 'id', 'title') %>
  <%= f.select :section_id,  options %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<%= render "form" %>

app/views/lessons/new.html.erb
<h1>Add Lessons</h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<h1><%= @course.title %></h1>
<h2><%= @section.title %></h2>
<h3><%= @lesson.title %></h3>
<p><%= @lesson.content %></p>

<p><%= link_to @section.title, section_path(@section.id) %></p>

app/views/sections/_form.html.erb
<%= form_for @section do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <% weekOp = ['Pre-Work', 'Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5'] %>
  <%= f.select :week,  weekOp %>
  <% options = options_from_collection_for_select(@course, 'id', 'title') %>
  <%= f.select :course_id,  options %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit Section</h1>

<%= render "form" %>

app/views/sections/new.html.erb
<h1>Add Section</h1>

<%= render "form" %>

app/views/sections/show.html.erb
<h1><%= @course.title %></h1>
<h2><%= @section.title %></h2>

<% if @course.sections.any? %>
  <h4>Here are the lessons for this section:</h4>

  <ul>
    <% @section.lessons.each do |lesson| %>
      <li>
        (<%= lesson.day %>) <%= link_to lesson.title, lesson_path(lesson) %> /
        <%= link_to "Edit", edit_lesson_path(lesson) %> /
        <%= link_to "Delete", lesson_path(lesson),
                               :data => {:confirm => "Are you sure?",
                                              :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no sections yet!</p>
<% end %>

<p><%= link_to @course.title, course_path(@course.id) %></p>